language: node_js
node_js:
  - 12

cache:
  directories:
    - 'node_modules'

branches:
  only: main

# before_install:
#   - npm install

install:
  - npm install


script:
  - npm run lint
  - npm run test:unit
  - npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --exit-zero-on-changes
# jobs:
#   include:
#     - name: 'ES Lint'
#       script: npm run lint

#     - name: 'Unit test'
#       script: npm run test:unit

#     - name: 'Public to Chromatic'
#       if: (type = push OR head_repo != repo )
#       script: npx chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --exit-zero-on-changes